mnid expects network id in hex format
Following error occurs if you use 5777 for network id

Error: Network id 0x77 is not configured
    at callRegistry (/Users/rjc/Projects/DLT_Project/uport/experiments/node_modules/uport-lite/lib/index.js:156:16)
    at get (/Users/rjc/Projects/DLT_Project/uport/experiments/node_modules/uport-lite/lib/index.js:196:14)
    at Promise (/Users/rjc/Projects/DLT_Project/uport/experiments/node_modules/uport-client/index.js:216:15)
    at new Promise (<anonymous>)
    at UPortClient.registry (/Users/rjc/Projects/DLT_Project/uport/experiments/node_modules/uport-client/index.js:215:37)
    at UPortClient.getDDO (/Users/rjc/Projects/DLT_Project/uport/experiments/node_modules/uport-client/index.js:317:17)
    at UPortClient.writeDDO (/Users/rjc/Projects/DLT_Project/uport/experiments/node_modules/uport-client/index.js:322:16)
    at consume.then.then.receipt (/Users/rjc/Projects/DLT_Project/uport/experiments/node_modules/uport-client/index.js:299:27)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)